# Default configuration for the local voice agent.
# CLI flags override these values at runtime.
ollama_model: "llama3.1"
ref_audio: "assets/voice/reference.wav"
ref_text: "assets/voice/reference.txt"
tts:
  backbone_repo: "neuphonic/neutts-air"
  backbone_device: "cpu"
  codec_repo: "neuphonic/neucodec"
  codec_device: "cpu"
